"""adds to charachter model

Revision ID: 010043342e1a
Revises: cd18fa91af11
Create Date: 2024-09-07 07:45:13.307922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '010043342e1a'
down_revision: Union[str, None] = 'cd18fa91af11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('star_wars_characters', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('star_wars_characters', 'rating')
    # ### end Alembic commands ###
