"""Create star wars characters table

Revision ID: e7b1f1b1b1b4
Revises: 518820f9216c
Create Date: 2024-09-07 06:55:52.503072

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e7b1f1b1b1b4"
down_revision: Union[str, None] = "518820f9216c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "star_wars_vehicles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("model", sa.String(), nullable=True),
        sa.Column("manufacturer", sa.String(), nullable=True),
        sa.Column("cost_in_credits", sa.String(), nullable=True),
        sa.Column("length", sa.String(), nullable=True),
        sa.Column("max_atmosphering_speed", sa.String(), nullable=True),
        sa.Column("crew", sa.String(), nullable=True),
        sa.Column("passengers", sa.String(), nullable=True),
        sa.Column("cargo_capacity", sa.String(), nullable=True),
        sa.Column("consumables", sa.String(), nullable=True),
        sa.Column("vehicle_class", sa.String(), nullable=True),
        sa.Column("pilots", sa.String(), nullable=True),
        sa.Column("efficiency", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("star_wars_vehicles")
    # ### end Alembic commands ###
